# Generated by Django 4.2.23 on 2025-08-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_epic_task_subtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='color',
            field=models.CharField(blank=True, default='#fafafa', max_length=7),
        ),
    ]
